### ISSUE TITLE
Typo in Team selector tooltip

### ISSUE THREAD

**Issue by Peleccotur** [Vapok/CommunityDKP#103]
Release 3.1.2-r45 contains a type in the tooltip for the team selector dropdown

![image](https://user-images.githubusercontent.com/24406001/87339423-de871a00-c546-11ea-9469-9d1f0f8bc8d2.png)

I don't think you need more info, otherwise Im happy to provide it.

**Comment by Vapok** [comment]
Should be fixed in the next release. r46
