### ISSUE TITLE
Announce Higest Bid & Bidder in Raid Warning instead of Raid Chat

### ISSUE THREAD

**Issue by The-Kru** [Vapok/CommunityDKP#104]
**Is your feature request related to a problem? Please describe.**
Feature is not related to a problem.

**Describe the solution you'd like**
Add a checkbox, that changes default announcing Highest Bid & Bidder to Raid-warning.

**Describe alternatives you've considered**
None considered so far.

**Additional context**
We are often bidding while fighting and things can get messy and people can lose track, if highest bidder and bid is announced to Raidwarning it is more prevalent in people's mind.

**Comment by Vapok** [comment]
![image](https://user-images.githubusercontent.com/1264136/87891574-72099080-ca08-11ea-9ee7-7bad470413bc.png)

This will be included in the next release.
