### ISSUE TITLE
Wrong localisation in the role column

### ISSUE THREAD

**Issue by f90** [Vapok/CommunityDKP#107]
**Describe the bug**
For German localisation, for tanks in the DKP table, the role column shows "Panzer", whereas it should be "Tank". What is confusing is that "Tank" is already in the German localisation:

https://github.com/Vapok/CommunityDKP/blob/d30a98d327f75da90ba09b73ef30e26f7926a2d1/Localization/Localization.de.lua#L688

But still it shows differently for me.

Same problem with range dps (Hunter). It shows as "Bereich DPS" when actually the localisation says "Fernkampf-DPS":

https://github.com/Vapok/CommunityDKP/blob/d30a98d327f75da90ba09b73ef30e26f7926a2d1/Localization/Localization.de.lua#L575

So something very weird is going on with the role translations in general??

Version 3.1.2-r45

**Comment by Vapok** [comment]
@f90 So I have figured out what's going on....and it's kind of funny.  Kind of sad.  About 7 months ago there was a Localization change that changed a few german words.  Panzer to Tank was one of those changes.  But the way that Monolith (and Community) store data is that it doesn't pull class information if it already has it, and it stores the localized version of the word in the database. So prior to 7 months ago, you added a tank and it was stored as Panzer.  If you were to create a new team, with a new table, and add that same player, you'll see "Tank" show up. 

Here's the git blame on the localized file from 7 months ago:
![image](https://user-images.githubusercontent.com/1264136/87562016-7261fe80-c68b-11ea-91c3-af70eb7f2cf5.png)

If the tank ever changed his talents, this would get updated to reflect the new localization.

Short of forcing excessive update calls for changing the class every time, there's not an easy way to fix this.

**Comment by f90** [comment]
Thanks for looking into this. Guess I will force my tank to respec then :D Well it's not a big problem at all, and with a new database it would be fixed. Also new users won't have this problem. So if you want you can close this issue in my book. Except if you decide to change the way these talent strings are loaded/stored within the addon?

**Comment by Vapok** [comment]
@f90  I'm putting in, what I think might be a fix for this. Basically, it should be updating this each time the player logs in and you're online, or when he zones into a new instance.
