### ISSUE TITLE
Hotkey to start awarding of an Item quickly from the inventory or item links

### ISSUE THREAD

**Issue by Eightball82** [Vapok/CommunityDKP#110]
Is your feature request related to a problem? Please describe.
Problem: Starting awarding of an Item with /dkp award [item] is slow and tedious
Sould work similar as #105 with auctions.

Describe the solution you'd like
When pressing a certain key combination (should be configurable), e.g. shift+alt, then the item in the inventory that the mouse cursor is currently hovering over should be used to open the award item setup window, just like /dkp award [item]

**Comment by Vapok** [comment]
This will already be included in the next release.  Hover over any piece of loot in loot window or bags and press LALT-LSHIFT.

**Comment by Vapok** [comment]
ohh.. "Awarding"  -- Hrm, you can reach the award screen via the bid screen.  Do you frequently use the /dkp award and not /dkp bid?

**Comment by Vapok** [comment]
Alright, I put an initial implementation of this in r46.  To activate, hit Left shift + Left Ctrl while hovering over an item.

**Comment by Eightball82** [comment]
> ohh.. "Awarding" -- Hrm, you can reach the award screen via the bid screen. Do you frequently use the /dkp award and not /dkp bid?

Yes, we roll Items for second needs, but charge a static DKP amount. Therefore I use the awarding-feature frequently.

**Comment by Eightball82** [comment]
Thanks for the quick response and implementation :-)
