### ISSUE TITLE
Standby Opt In message broadcast where raid is not initialized.

### ISSUE THREAD

**Issue by Staz5817** [Vapok/CommunityDKP#111]
Thanks so much for taking over Monolith and further improving it. While on a non dkp earning raid today became aware of the lovely change put in place to not give out dkp if the raid hasn't been initialized (this has caught us out so many times so it is a very welcoming feature). 

The !standby message was broadcast even though the raid wasn't initialized. I am unsure whether someone replying would have caused dkp to be applied as no one replied. As this activated on boss kill I am unable to test further until our next non dkp raid but logically it makes more sense for the message to be disabled unless a raid is initialized.

**Comment by Vapok** [comment]
Will be deployed in the next release.
