### ISSUE TITLE
Bid messages are printed to all chat windows.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [Vapok/CommunityDKP#116]
**Describe the bug**
A clear and concise description of what the bug is. This includes the following information:

1) Addon Version and Release e.g. 3.0.0-r7
v3.1.3-r47
2) What are your DKP Modes? (screenshot preferred)
I'm not sure what this is.
3) What is the issue you're seeing (screenshot preferred)
When a bid is initiated the bid messages including initial bid message with item link, countdown, and final result message, are printed to all chat windows.

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**To Reproduce**
1. Group in a raid.
2. Kill a boss.
3. Initiate a bid on a drop.

**Expected behavior**
The addon should only print to one window. At least just the General window but preferably a customizable window.

**Screenshots**
I think this is clear enough that screenshots are not necessary. Please let me know if they are.

**CommunityDKP Version**
Noted above.

**Additional context**
None.

**Comment by Vapok** [comment]
@Chalos-Atiesh  This is not actually a bug, but rather a feature, and you have some settings that can control this. On the Options Tab, there's a drop down for "Addon Notifications.

Select which channel you want notifications going to:
![image](https://user-images.githubusercontent.com/1264136/88062467-df1b4400-cb36-11ea-8f50-276fa4e0c88c.png)

**Comment by Chalos-Atiesh** [comment]
... I must be blind. Apologies. And thanks!

**Comment by Chalos-Atiesh** [comment]
After thinking about it for a bit I have one more question. Is there a reason it prints to _every_ chat frame by default? Would it be less annoying to the user if it picked one chat frame initially and set that? Then, if the user wanted more or other chat frames they could use this dropdown?

**Comment by Vapok** [comment]
We'll take a look at it.  maybe it was easier to just loop through and check all channels by default than specifically try and do general only.  maybe just lazy coding.
