### ISSUE TITLE
Using '/dkp reset' does not reset all window positions

### ISSUE THREAD

**Issue by Anonomit** [Vapok/CommunityDKP#118]
The bid timer window, as well as both bidding windows, do not reset their positions on /dkp reset.

1. /dkp bid
2. Move windows
3. Options -> Move bid timer
4. Move the bid timer
5. Options -> Hide bid timer
6. /dkp reset
7. Issue: Bid timer and bidding windows have not been reset

Notably, if the bid timer window is visible while using /dkp reset, then it is correctly moved to the middle of the screen. This is not the case with BiddingWindow or BidderWindow - they appear to never reset.

v3.1.3-r47

**Comment by Vapok** [comment]
making sure all positions are reset. will be in next release.
