### ISSUE TITLE
Custom Minimum Bid Values Changing after Bidding

### ISSUE THREAD

**Issue by Geronymo17** [Vapok/CommunityDKP#119]
**Is your feature request related to a problem? Please describe.**

My guild uses a lot of custom values in a minimum bid DKP setup. So let's say the Ashkandi minimum bid custom value is 80 DKP. When someone gets the Item for 200 DKP, the custom minimum is changed to 200 DKP and won't stay at 80.

**Describe the solution you'd like**

It would be great if the custom values would stay again at the value we chose. An even better feature would be if you could change custom values of item in some kind of table, e. g. in an Edit-Button in the Pricing-Tab.

**Describe alternatives you've considered**

Manually changing every custom value back when the item drops. This is exhausting, of course.

**Additional context**
Our DKP settings:
![image](https://user-images.githubusercontent.com/57114704/88219273-a4fa9100-cc61-11ea-9909-3cf3bcc6f383.png)

Thanks as always, Vapok!

**Comment by sarahbau** [comment]
I've noticed this too, except I never wanted to have custom values at all. Every item is now setting a custom value. When I open a bid for a previously DEd item, it starts the bidding at 0 rather than the 10 that we have as the minimum bid. As far as I can tell, there's no way to remove custom values without manually editing the lua file.

**Comment by sarahbau** [comment]
![settings_1](https://user-images.githubusercontent.com/12877384/88245884-a1f5a580-cc4d-11ea-9550-ccdb0892cf70.jpg)
![settings_2](https://user-images.githubusercontent.com/12877384/88245887-a621c300-cc4d-11ea-8aef-906801f82e53.jpg)
![prices](https://user-images.githubusercontent.com/12877384/88245893-ac17a400-cc4d-11ea-97af-c8cea6b204a7.jpg)
![starting_high](https://user-images.githubusercontent.com/12877384/88245898-b2a61b80-cc4d-11ea-982e-fdca387b4784.jpg)
![starting_zero](https://user-images.githubusercontent.com/12877384/88245904-b6d23900-cc4d-11ea-9996-02d4d2f5ef0a.jpg)

**Comment by Vapok** [comment]
I appreciate the effort you went to @sarahbau on these screenshots, and the video. Sorry I couldn't watch the video. =)  

That being said, I think I finally tracked down the small needle.  It was a change I made to an if statement that didn't have an else, and I created one. I think that not understanding how it was being used in a live environment was a factor in the bug and slowness to resolve.

Can you please test out 3.1.3-r48 and let me know?  Based on how this works, only the officer performing the bids needs to update their addon, and it should synchronize the min bid appropriately.

Thanks

**Comment by sarahbau** [comment]
@Vapok The video is in the other recent ticket :)

I downloaded r48, but also just went ahead and modified the lua file to remove prices. However, as I was doing that, I noticed that it seems like there's no way to mark something as disenchanted, without creating an override for the price. I tried just removing the `["minbid"] = 0` attribute for one of the items. As I hoped, it still showed up in the list with the number of disenchants, and now didn't have a price associated with it. However, when I tried opening a new bid for that item, I got a lua error (nil value trying to read minbid).

I deleted all items with 0 disenchants, and updated the minbid of all disenchanted items to 10, and this worked (items not on the list still start at 10, and items that have been disenchanted still start at 10), but I have a feeling that future disenchanted items will still get minbid set to 0, is that correct?

Maybe my way of bidding is unusual, but I basically want all items, whether they're expected to be high price or expected to be disenchanted, to start at the same price every time (currently 10, but I might want to change that in the future). I guess I could just stop clicking "DE" for items that get DEed, but I like the tracking.

Speaking of tracking...(I know this is kind of getting off topic for this ticket, but...) I liked that the prices tab shows the price that things last went for - I just don't want that to be the price the item starts at next time. It would be nice to still track that (and maybe total drops as well). It's currently kind of  unwieldy to try to find how many times any item has dropped. You have to find someone you know has it, then mouse over them to see who else has won it.

**Comment by Geronymo17** [comment]
Hi @Vapok @sarahbau ,

I've just tested your new version. While the minimum bid doesn't start with the last price (or 0 in case of disenchanted items), it goes back to the standard minimum bid value instead of the custom value.

Here is an example with Neltharion's Tear. The custom value was 40 DKP. After I won the the auction and put the item back in again for bidding the minimum bid value goes back to the standard value of 20.

![image](https://user-images.githubusercontent.com/57114704/88413409-6ee11c80-cddb-11ea-8327-db336a488ef6.png)

Is there another way to fix this?

Thanks again for your help!

**Comment by Vapok** [comment]
@sarahbau I love your input above. Let me noodle on this.  @Geronymo17 this is the kind of feedback I'm DEFINITELY looking for.  Are you running the same mode that Sarah is?

**Comment by Vapok** [comment]
r49 has what I feel is the proper fix.  I spent about 4 hours on this today. lol

**Comment by Vapok** [comment]
@sarahbau - Have you had a chance to see if this has been corrected?
