### ISSUE TITLE
Contextual menu in roster doesn't stay open

### ISSUE THREAD

**Issue by sarahbau** [Vapok/CommunityDKP#120]
**Describe the bug**
When right clicking on a member in  the roster (usually when I want to add or remove someone from standby, the contextual menu that pops up will often close after a second. I will have to do this a few times before it stays open and I can actually use it. There is also a brief lag in the game when this happens (video pauses)

1) Version 3.1.3-r47 (though I have experienced this going back to MonolithDKP)
2) What are your DKP Modes? 
3) What is the issue you're seeing (screenshot preferred)

![contextual_menu](https://user-images.githubusercontent.com/12877384/88244407-9f448180-cc48-11ea-8b1f-b8ddfcc551e8.gif)

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**To Reproduce**
1. Wait for CommunityDKP  to fully initialize
2. Open CommunityDKP (/dkp)
3. Right click on any user

**Expected behavior**
The contextual menu will open and remain open, allowing the user to pick one of the menu items

**Screenshots**
See above

**CommunityDKP Version**
(e.g. 3.1.3-r47)

**Additional context**
This has been occurring since MonolithDKP

**Comment by Vapok** [comment]
I actually caught a similar issue to this myself, and then it was followed by a LUA error, being thrown off by a TitanPanel piece of code that appears to be getting activated.  Reloading the UI seems to fix it,

It's only happened to me once though and a UI reload fixed it.

I can't reproduce this otherwise.

**Comment by ggwalsh** [comment]
As per discord, same thing happening with me - disabling Titan Panel seemed to fix the issue for me.

All addons are attached - note some are usually disabled anyway.

https://1drv.ms/u/s!AmrpyGKughkBgoVp6TMqjMdsdpHPbw?e=xGB1Wr

**Comment by sarahbau** [comment]
I disabled every addon other than CommunityDKP

Issue remained

Did `/reload`

Issue remained

Restarted WoW entirely (with all but CommunityDKP still disabled)

Issue remained

CommunityDKP.lua attached
[CommunityDKP.zip](https://github.com/Vapok/CommunityDKP/files/4971958/CommunityDKP.zip)

**Comment by Anonomit** [comment]
#123 should fix this. The right-click context menu will now appear instantly. The issue was because of your large guild size and dkp table.

**Comment by Vapok** [comment]
Thanks to @Anonomit for his help with that. The perils of not using a large dataset.  This will go out on the next release.
