### ISSUE TITLE
LUA Errors on awarding

### ISSUE THREAD

**Issue by sneezyo** [Vapok/CommunityDKP#122]
**Describe the bug**
For two weeks in a row after Flamegor when doing /dkp bid [item] a LUA errors pops up, forcing me to /reload
Also when Awarding an item the LUA errors popped up. Maybe a coincidence but it happened 2 raids in a row after Flamegor, before the Chromaggus packs.

EDIT: I see I only saved 1 lua error (according to the lua it's the 'award' error)

1) Addon Version and Release
3.1.3-r47
2) What are your DKP Modes? (screenshot preferred)
![image](https://user-images.githubusercontent.com/68755154/88431255-40266e80-cdfa-11ea-9e7d-f4aa6a54e997.png)

3) What is the issue you're seeing (screenshot preferred)
LUA errors posted below

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**To Reproduce**
1. Go to after Flamegor
2. Click on /dkp bid [item] (tested with multiple items)
3. press 'Started Bidding'
4. See error (posted below) EDIT: I see I only saved 1 lua error (according to the lua it's the 'award' error)

Issue 2: 
1. Go to after Flamegor
2. Click on /dkp bid [item] (tested with multiple items)
3. press 'Started Bidding'
4. Press any raid member who bidded and selected 'Award Item'
5. See error (posted below)

**Expected behavior**
No error shown

**Screenshots**

**CommunityDKP Version**
3.1.3-r47

**Additional context**
Error when pressing 'Award item)

EDIT: When creating this issue I noticed I only saved one LUA error instead of both

Date: 2020-07-23 20:36:24
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\Core.lua line 145:
   bad argument #1 to 'format' (number expected, got nil)
Debug:
   [C]: format()
   CommunityDKP\Core.lua:145: CommDKP_round()
   CommunityDKP\Modules\Award.lua:195:
      CommunityDKP\Modules\Award.lua:34
   CommunityDKP\Modules\Award.lua:588:
      CommunityDKP\Modules\Award.lua:573
Locals:
(*temporary) = "%.0f"
(*temporary) = nil
(*temporary) = "number expected, got nil"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.2
  AtlasLootClassicData, vv1.5.2
  AtlasLootClassicDungeonsAndRaids, vv1.5.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.05
  ClassicAuraDurations, v1.13.60
  CommunityDKP, v3.1.0
  DBMBWL, v
  DBMCore, v1.13.53
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ExRT, v4160
  ExtendedCharacterStats, v2.4.6
  HealCommClassic, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.73
  LeatrixPlus, v1.13.73
  MikScrollingBattleText, v5.7.150
  ModernTargetFrame, v1.8
  NovaWorldBuffs, v1.71
  OmniBar, vv10.8
  OmniCC, v8.3.5
  Quartz, v3.5-classic-5
  Questie, v6.0.2
  RaidFrameIndicators, v2.6.2a
  RingMenu, v2.2.1
  RollTrackerClassic, v2.21
  Spy, v1.1.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TellMeWhen, v8.7.5
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  WeakAuras, v2.17.12
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=6f9)

**Comment by Vapok** [comment]
Fixed LUA error.. Will be released on next release.
