### ISSUE TITLE
Highlighting items with shift + click pressed opens award screen

### ISSUE THREAD

**Issue by wysun7** [Vapok/CommunityDKP#124]
**Describe the bug**
A clear and concise description of what the bug is. This includes the following information:

1) Addon Version and Release e.g. 3.0.0-r7

CommunityDKP-3.1.3-r50

2) What are your DKP Modes? (screenshot preferred) N/A - not a guild officer
3) What is the issue you're seeing?

Any time shift + ctrl is pressed with an item highlighted, a popup happens to award that item as loot. As someone who doesn't award loot using the addon, this is quite annoying since it doesn't apply to me. 

Also, if this is intended behavior for distributing loot (I'm not an officer in my guild, so I'm not familiar with all of the hotkeys or expectations), as someone who would distribute loot, I would expect this to happen when an item is **clicked** with ctrl + shift pressed, which is more intentional than just highlighting an item with ctrl + shift pressed.

**To Reproduce**
1. Highlight an item - this can be in your bags or even equipped items
2. Press shift + ctrl
3. Award screen pops up

**Expected behavior**
Expect this not to happen, especially as someone who is not an officer in the guild (I don't award loot using the addon). If I were to award loot, I would also expect that this popup happens only if the item is clicked.

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/69024114/88993069-c844c200-d299-11ea-8efa-2a9e68963ebe.png)

**CommunityDKP Version**
(e.g. 3.0.0)
CommunityDKP-3.1.3-r50

**Additional context**

**Comment by Vapok** [comment]
The Shift+Ctrl is by design. But it should be filtering by officer, and looks like it's not.

**Comment by Vapok** [comment]
This now only activates if the player is an officer.  Will be updated on next release.
