### ISSUE TITLE
New Boss Kill DKP bonus setting ignored

### ISSUE THREAD

**Issue by cr0ok** [Vapok/CommunityDKP#129]
Seems the New Boss Kill bonus DKP amount isn't applied to new boss kills.  In AQ40 last week, none of us had killed any of the bosses yet, even on alts, and even though the raid leader had the desired value set for the New Boss Kill bonus (20), the "normal" boss kill bonus was applied (5).  When we first saw the issue after the first boss kill, the raid leader did a /reload to make sure the setting was in effect, but it didn't make a difference.

**Comment by Vapok** [comment]
@cr0ok - New Boss DKP is not used in the automatic settings, as the addon can't know for sure if it's truly a new boss kill.  That value is used though when using the Adjust DKP tab to manually apply New Boss Kill DKP to selected profiles.

**Comment by cr0ok** [comment]
Got it - thanks Vapok!
