### ISSUE TITLE
Prevent auto DKP when no raid is initialized

### ISSUE THREAD

**Issue by joheri85** [Vapok/CommunityDKP#14]
We dont use DKP for some raid, Onyxia for example.
But if i have the addon setup like i want it for DKP-raids it will still auto award bosskill for Onyxia.

We use both time based DKP and Bosskill DKP.

so what would be great is an option to only award DKP automatically when a raid is initialized.

So in essence, 
When autoaward dkp for bosskills is enabled
check if the tick box "Raid auto award only" is checked when a boss dies.

If YES check if a raid is started 
      if YES award dkp 
      if NO Dont award dkp
if NO award dkp

**Comment by thunk84** [comment]
Following the comments for issue 363 on original Monolith, in v2.2.9beta, adjusting line init.lua'275 (inside OnEvent, if event == BOSS_KILL) to the following solves the problem of awarding DKP with no raid session: 
`
if core.IsOfficer and IsInRaid() and core.RaidInProgress then	--QFIX, from Mono bug 363`

**Comment by Vapok** [comment]
Will be updated on next release.
