### ISSUE TITLE
MonolithDKP backwards compatibility

### ISSUE THREAD

**Issue by perara** [Vapok/CommunityDKP#141]
It should come pretty clear in the docs if this addon is compatible with guilds running Monolith. 

Monolith got approx 99% of the "market share" in terms of DKP management addons and keeping CommunityDKP compatible with the MonolithDKP guilds (individual members) would increase your userbase significantly.

**Comment by Vapok** [comment]
MonolithDKP is a dead addon, abandoned by the author. Made clear no further updates on that addon. 

CommunityDKP won't run when MonolithDKP is installed but will offer a migration path.

Users are free to continue using a non-support addon or migrate to something that has carried the original intent of the addon further, which is CommunityDKP.  

I'm not seeking backward compatibility. I'm seeking a replacement.

**Comment by perara** [comment]
That is a fair, point, but this should perhaps be clear fairly early in the documentation that CommunityDKP aims to **replace** MonolithDKP and cannot function for players in a Monolith DKP guild :)
