### ISSUE TITLE
Lua errors/warnings - CommunityDKP does not work

### ISSUE THREAD

**Issue by vendh** [Vapok/CommunityDKP#142]
1) Addon Version and Release e.g. 3.0.0-r7
_CommunityDKP-3.2.3-r60.zip_

2) What are your DKP Modes? (screenshot preferred)
_Minimum Bid_

3) What is the issue you're seeing (screenshot preferred)
_Multiple lua errors/warnings_

**Additional context**
I'm getting multiple lua errors/warnings when logging in (see below) since one of the latest updates (CommunityDKP worked fine before). Moreover, when I trype /dkp it says "Your DKP Modes settings have changed and can not run that until your UI is reloaded". When I reload UI and type /dkp the same message appears again.

Here are the lua errors/warnings:

----------------------------------------------------------------------------------

Date: 2020-09-15 09:28:20
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\Modules\Sync.lua line 8:
   Cannot find a library instance of "AceSerializer-3.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: GetLibrary()
   CommunityDKP\Modules\Sync.lua:8: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "AceSerializer-3.0"."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.3
  ClassicGuildBank, v1.3
  CommunityDKP, v3.2.3
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=307)

----------------------------------------------------------------------------------

Date: 2020-09-15 09:28:20
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\Modules\comm.lua line 10:
   Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
Debug:
   [C]: ?
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:189: EmbedLibrary()
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:171: EmbedLibraries()
   ...\ClassicGuildBank\libs\AceAddon-3.0\AceAddon-3.0.lua:138: NewAddon()
   CommunityDKP\Modules\comm.lua:10: in main chunk
Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0"."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.3
  ClassicGuildBank, v1.3
  CommunityDKP, v3.2.3
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=307)

----------------------------------------------------------------------------------

Date: 2020-09-15 09:34:08
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\Localization\Localization.lua line 1:
   unexpected symbol
Debug:
   
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.3
  ClassicGuildBank, v1.3
  CommunityDKP, v3.2.3
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=307)

----------------------------------------------------------------------------------

Date: 2020-09-15 09:34:12
ID: 4
Error occured in: Global
Count: 1
Message: [string "--[==[ Error in 'BWL Entrance Auto Orb Goss..."] line 3:
   attempt to index local 'title' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "--[==[ Error in 'BWL Entrance Auto Orb Goss..."]:3:
      [string "--[==[ Error in 'BWL Entrance Auto Orb Goss..."]:1
   [C]: xpcall()
   WeakAuras\GenericTrigger.lua:605:
      WeakAuras\GenericTrigger.lua:541
   WeakAuras\GenericTrigger.lua:812: ScanWithFakeEvent()
   WeakAuras\GenericTrigger.lua:1106: LoadDisplays()
   WeakAuras\WeakAuras.lua:2382: LoadDisplays()
   WeakAuras\WeakAuras.lua:2215:
      WeakAuras\WeakAuras.lua:2099
   WeakAuras\WeakAuras.lua:2323: ReloadAll()
   WeakAuras\WeakAuras.lua:1955: ScanAll()
   WeakAuras\WeakAuras.lua:1901: Resume()
   WeakAuras\WeakAuras.lua:1719:
      WeakAuras\WeakAuras.lua:1670
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CharacterStatsClassic, v3.6.3
  ClassicGuildBank, v1.3
  CommunityDKP, v3.2.3
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  GatherMate2, v1.45.5
  HealBot, v1.13.5.3
  HealBotData, v1.13.5.3
  HealBoten, v1.13.5.3
  HealBotOptions, v1.13.5.3
  HealBotTips, v1.13.5.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LibStub, v
  Mapster, v1.8.5
  NovaWorldBuffs, v1.79
  Questie, v6.0.5
  RCLootCouncilClassic, v0.11.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  TradeSkillMaster, vv4.10.5
  TradeSkillMasterAppHelper, vv4.0.8
  tukui, v1.38
  VendorPrice, v1.3.6
  WeakAuras, v2.18.4
  WIM, v3.8.14
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=75b)

----------------------------------------------------------------------------------

Date: 2020-09-15 09:34:17
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\init.lua line 295:
   attempt to index field 'Sync' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [C]: ?
   CommunityDKP\init.lua:295:
      CommunityDKP\init.lua:288
Locals:
errMsg = "Interface\AddOns\CommunityDKP\init.lua:295: attempt to index field 'Sync' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CharacterStatsClassic, v3.6.3
  ClassicGuildBank, v1.3
  CommunityDKP, v3.2.3
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  GatherMate2, v1.45.5
  HealBot, v1.13.5.3
  HealBotData, v1.13.5.3
  HealBoten, v1.13.5.3
  HealBotExtraSkins, v1.13.5.3
  HealBotOptions, v1.13.5.3
  HealBotTips, v1.13.5.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LibStub, v
  Mapster, v1.8.5
  NovaWorldBuffs, v1.79
  Questie, v6.0.5
  RCLootCouncilClassic, v0.11.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  TradeSkillMaster, vv4.10.5
  TradeSkillMasterAppHelper, vv4.0.8
  tukui, v1.38
  VendorPrice, v1.3.6
  WeakAuras, v2.18.4
  WIM, v3.8.14
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=77a)

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml(1): error: not well-formed (invalid token)
Time: Tue Sep 15 09:34:13 2020
Count: 4

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Libs\AceAddon-3.0\AceAddon-3.0.xml(1): error: not well-formed (invalid token)
Time: Tue Sep 15 09:34:13 2020
Count: 4

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Libs\AceComm-3.0\AceComm-3.0.xml(1): error: not well-formed (invalid token)
Time: Tue Sep 15 09:34:13 2020
Count: 4

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Libs\ChatThrottleLib\ChatThrottleLib.xml(1): error: not well-formed (invalid token)
Time: Tue Sep 15 09:34:13 2020
Count: 4

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Libs\AceSerializer-3.0\AceSerializer-3.0.xml(1): error: not well-formed (invalid token)
Time: Tue Sep 15 09:34:13 2020
Count: 4

----------------------------------------------------------------------------------

Message: (null)
Time: Tue Sep 15 09:34:13 2020
Count: 6

----------------------------------------------------------------------------------

Message: Interface\AddOns\CommunityDKP\Localization\Localization.lua:1: unexpected symbol
Time: Tue Sep 15 09:34:13 2020
Count: 3

**Comment by ixidion** [comment]
Where did you download it? Twitch/Curse, Release from this site, Git-Repo from here?

**Comment by vendh** [comment]
I use Twitch to download and update Addons.

**Comment by Vapok** [comment]
@vendh  These error messages are suggesting that you are missing a number of files that are included in the addon package.  It's almost like maybe you're missing all of the external libraries. I would completely remove CommunityDKP from the Addons folder and redownload from Twitch.

**Comment by vendh** [comment]
Manually deleting the whole CommunityDKP folder and reinstalling using Twitch worked. Thanks!
