### ISSUE TITLE
On-time and interval bonuses not given to raiders on standby

### ISSUE THREAD

**Issue by sarahbau** [Vapok/CommunityDKP#151]
**Describe the bug**
1) Addon Version and Release: 3.2.3-r60
2) What are your DKP Modes? (see screenshots)
3) What is the issue you're seeing?

When raiders are on the standby list, they receive neither on-time/raid end bonuses, nor time interval bonuses. They do receive boss kill bonuses. This is despite the "include standby" option for raid initialization being checked. See in screenshots: Holyknight, Tigolebitys, Merlinn, and Smellulater each received boss kill dkp for C'thun and Viscidus, but are neither in their own group of bonus DKP for interval/end, nor in the group of raiders who received it.

**To Reproduce**
1. Set options to auto-award dkp, including standby, and to not require standby opt-in
2. Initialize a raid with on-time/end/interval bonuses, with the "include standby" option checked
3. Observe that standby members get boss kill dkp, but no bonus dkp.

**Expected behavior**
All standby members should get both boss kill and raid start/end/interval bonuses.

**Screenshots**
![settings_1](https://user-images.githubusercontent.com/12877384/98488458-142ecd80-21de-11eb-8af7-32749108c9bc.jpg)
![settings_2](https://user-images.githubusercontent.com/12877384/98488460-17c25480-21de-11eb-80c9-448a18f4121a.jpg)
![init_settings](https://user-images.githubusercontent.com/12877384/98488463-1abd4500-21de-11eb-949e-20ed5e6fb243.jpg)
![dkp_history](https://user-images.githubusercontent.com/12877384/98488467-1ee96280-21de-11eb-8e63-6e97b02c5742.jpg)

**CommunityDKP Version**
3.2.3-r60

**Comment by Taidtuskecyh** [comment]
Hi,

I think your problem is the 'Online Only' checkbox. Not sure why it applies to standby but it does.
As you can see below, auto awarding works for standby list (taken from my last raid)

![image](https://user-images.githubusercontent.com/23189953/98663320-34c76680-2349-11eb-81a1-2dd8258a89ac.png)


```
if #CommDKP:GetTable(CommDKP_Standby, true) > 0 and core.DB.DKPBonus.IncStandby then
	local i = 1
	while i <= #CommDKP:GetTable(CommDKP_Standby, true) do
		local standbyProfile = CommDKP:GetTable(CommDKP_Standby, true)[i].player;
		local isOnline = UnitIsConnected(standbyProfile);
		if strfind(tempList, standbyProfile) then
			table.remove(CommDKP:GetTable(CommDKP_Standby, true), i)
		else
			if standbyProfile and (not OnlineOnly or isOnline) then
			    CommDKP:AwardPlayer(standbyProfile, amount)
			    tempList = tempList..standbyProfile..",";
			end
				i=i+1
		end
	end
end
```
