### ISSUE TITLE
Allow ability to import DKP values from CSV

### ISSUE THREAD

**Issue by pjeli** [Vapok/CommunityDKP#152]
Our guild has long been maintaining a DKP sheet on Google Docs and while we would love to use something like CommunityDKP instead for the automation but we cannot because the data entry task is too great.

If there could be a way to import DKP values from a CSV-style bulk entry would be very helpful.

Thanks.

**Comment by Taidtuskecyh** [comment]
In what way? Do you want to import the entire history or just current Player-DKPValue ?

**Comment by pjeli** [comment]
Just the current player DKP values is enough. Maybe a way to have a note in the history so I can log “imported from google doc”, but that is extra.

Just the import of current player DKP values would be enough to initialize and we can build history from there.

Thanks for replying!

**Comment by Taidtuskecyh** [comment]
All I can really offer is a manual fix of the .lua file. 

If you have all the players in your guild, just add everyone to the DKP table, close down WoW and go into file edit.

The file will be at 
C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\<account name>\SavedVariables\CommunityDKP.lua

If you have successfully added people to your DKP table you can manually do CTRL+F in notepad++
["player"] = "playerName",

and edit the ["dkp"]=0 value for each player u have in your excel file.

If we are talking 40-50 people this shouldn't take longer than 20 min.

The file should look something like this
![image](https://user-images.githubusercontent.com/23189953/99117857-c14a8100-25f6-11eb-8a95-7717aaded7b3.png)

**Comment by pjeli** [comment]
Yeah @Taidtuskecyh - that's exactly what we did in the meantime.

The work was still pretty painful for us as we had a large list and we had to double check that we moved the numbers over correctly. If there was a built in way would be nice - but if its asking too much I understand.

Thank you.
