### ISSUE TITLE
Update CommunityDKP game version support

### ISSUE THREAD

**Issue by plchampigny** [Vapok/CommunityDKP#168]
**Describe the bug**
CommunityDKP game version shows 1.13.5 and cannot be installed on CurseForge app with the 2.5.1 game client

**To Reproduce**
Go to https://www.curseforge.com/wow/addons/communitydkp and check version being 1.13.5

**Expected behavior**
Game version should support 2.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/954879/119532200-ac436d00-bd52-11eb-85d1-2cd28922af0e.png)

**CommunityDKP Version**
3.2.6-r65-bcc

**Comment by Taidtuskecyh** [comment]
Same as #170  so closing this one
