### ISSUE TITLE
Chat message event race condition on UI startup

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#17]
Receiving a chat message event before 2.2.9 has fully initialized results in the following error (or slight variations depending on the message received):

Date: 2020-06-16 12:03:28
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\init.lua line 251:
   attempt to index field 'DB' (a nil value)
Debug:
   MonolithDKP\init.lua:251:
      MonolithDKP\init.lua:248
Locals:
self = EventsFrame {
 0 = <userdata>
}
event = "CHAT_MSG_WHISPER"
arg1 = "sorry that tell was for mip"

**Comment by Vapok** [comment]
Fixed and will be available in next release.
