### ISSUE TITLE
CommunityDKP (Game Version)

### ISSUE THREAD

**Issue by ailya1988** [Vapok/CommunityDKP#170]
Hi. Please update the Game Version to 2.5.1.
Due to the Game Version 1.13.5, CommunityDKP is not searched for by CurseForge Client.
![Screenshot_1](https://user-images.githubusercontent.com/63604281/119697093-856f5e80-be58-11eb-8ff2-61123af6cc38.png)

**Comment by Taidtuskecyh** [comment]
Hey,

I wish I could. I don't have access to Vapoks curse account. 
I have contacted curse in this matter but haven't heard from them yet

**Comment by cloverpi** [comment]
This project is GPL'd, it might be time for you to fork it and repost it as 'TBC Edition' on curseforge

**Comment by Taidtuskecyh** [comment]
there is a new project on Curseforge dedicated to TBC game version
