### ISSUE TITLE
There should be an option to auto master loot or trade the item to the winner.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [Vapok/CommunityDKP#172]
**Is your feature request related to a problem? Please describe.**
The user still has to manually select the winner and send the item to them. Why not have an opt-in way to automate that? Some users may not want it so it should be opt-in instead of opt out.

**Describe the solution you'd like**
PR to be issued shortly. If the user opts in the item should be automatically master looted to the winner if initiating the bid from the loot window. If initiating the bid from bags the item should be automatically added to trade windows to the winner until the trade is completed.

**Describe alternatives you've considered**
Not really sure there is an alternative fix to this.

**Additional context**
Here's the patch in action: https://www.dropbox.com/s/tp5763xyshc9in1/CDKP.mp4?dl=0

**Comment by Chalos-Atiesh** [comment]
And here's the PR: https://github.com/Vapok/CommunityDKP/pull/173

**Comment by Chalos-Atiesh** [comment]
And here's the PR: https://github.com/Vapok/CommunityDKP/pull/174
I had left some print statements in the previous PR.

**Comment by Taidtuskecyh** [comment]
#174
