### ISSUE TITLE
Update dot in left corner is not responding when clicked on.

### ISSUE THREAD

**Issue by travisderouen** [Vapok/CommunityDKP#177]
Version v3.2.8-r68.

1) Type /dkp to open up the DKP addon window.
2) Click the red/green dot in the bottom left corner.
3) Nothing happens.

I ran the /console scriptErrors 1 command in order to see any generated errors and this is the error that I received:
imgur link: https://i.imgur.com/OixAZnz.png
text:

Message: Interface\AddOns\CommunityDKP\Core.lua:516: attempt to index global 'f' (a nil value)
Time: Thu Jun 17 15:05:54 2021
Count: 1
Stack: Interface\AddOns\CommunityDKP\Core.lua:516: attempt to index global 'f' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\CommunityDKP\Core.lua"]:516: in function `CreateContainer'
[string "@Interface\AddOns\CommunityDKP\Modules\Sync.lua"]:345: in function `CommDKP_BroadcastFull_Create'
[string "@Interface\AddOns\CommunityDKP\Modules\Sync.lua"]:170: in function `CommDKP_BroadcastFull_Init'
[string "@Interface\AddOns\CommunityDKP\TableFunctions.lua"]:945: in function <Interface\AddOns\CommunityDKP\TableFunctions.lua:942>

Locals: 

I tried disabling all of my addons except CommunityDKP and it still wasn't working.

**Comment by cyclone701** [comment]
had the same issue about 10 mins ago

**Comment by Taidtuskecyh** [comment]
this was fixed in one of the previous versions
