### ISSUE TITLE
Full Sync Problems 

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#18]
Using 229beta, the guild leader renamed the initial, default team to "MC" then created a second team for "BWL." As expected, on startup, the existing data was picked up into the "MC" Team. We manually updated the BWL team.

We asked our guildies to blow away their old Monolith files and the officers will do a full push, as we wanted to make as clean of a start as possible.

The guildies log in, their table shows blank (as expected) and they only see one team, our guild name (also as expected). An officer sends a full push for both teams.

For a percentage of people, maybe 1 out of 4 or 1 out of 5, at the end of the push their team 1 data (MC) is actually shown in team 2 (BWL). Sometimes the team 1 data is blank, sometimes it's also populated. In all cases, having the player delete their wtf files again and receive a second push works fine.

So the core problem I'm reporting is that maybe 20% of the time, team 1 data is being pushed but showing up in team 2.

The secondary problem is that this happens randomly, regardless of whether you had prior data or not. When we tried to do a guild-wide push, some number of people (I'll say 20%) randomly received the problem... even if they already had good tables. In an attempt to fix those that were broken, an officer did another guild-wide push. Which broken a different random 20% of the recipients, again even they had previously good data.

At this point I interjected and stopped guild AOE pushes. Using only singletarget pushes, we still see the core problem every few tries, but the collateral damage is contained.

Although I can't exactly produce it on demand, it's happening enough that I'm sure I could get a repro in a few tries if there's any debugging info I can collect.

**Comment by thunk84** [comment]
Just to confirm my last comment, even though this is random, it seems to happen no more than 1-in-5 but no less than 1-in-10.

**Comment by thunk84** [comment]
one more update. Char A did a full push of team1 repeatedly to Char B. On the first 5 tries, Char B's team 1 was correctly updated. On the sixth try, the changes showed up incorrectly in Char B's team 2. At that point, Char B incorrectly showed exactly the same data on both Team1 and team 2.

**Comment by joheri85** [comment]
did you delete MonolithDKP folder in interface addons before you added the new one or did you just overwrite?

**Comment by Vapok** [comment]
This is a great recap of your experiences.  I think part of the issue stems from us trying to respect 2.1.2 backwards compatibility.   There's a variable that we're trying to sync as well.. So.. depending on how the comms work, if the variable doesn't get synced before the data gets synced, then I can see how this might happen.

This will lead to a version 2.3.0 that can be upgraded from 2.1.2, but not compatible with 2.1.2.

**Comment by thunk84** [comment]
@joheri85 this reply is probably too late now, but just to answer your question, we had everyone blow away the original monolith addon folder. Everyone except the guild leader also deleted the WTF files (or moved them to safe places). Only the guild leader imported the 2.1.2 data on first bringup of 2.2.9. The guild leader renamed/created the teams, and started pushing to others.

**Comment by Taidtuskecyh** [comment]
@thunk84 branch bugs/GH18 should have fixed this. But be aware this version will not be compatible with any previous version with anything but version check

**Comment by Vapok** [comment]
This has been resolved with the release of CommunityDKP v3.0.0

https://github.com/Vapok/CommunityDKP/releases/tag/3.0.0
