### ISSUE TITLE
Officer privileges being removed with logouts

### ISSUE THREAD

**Issue by nicb33** [Vapok/CommunityDKP#186]
I am ussing the classic communitydkp 3.2.9 for TBC, I recently recieved officer privileges for our team #2 (we currently have 3 teams in the same guild). It seems that every time I logout and log back in, my officer privleges are gone (do not have access to the manage tab and so on). The only way to get them back  form what i've attempted, is to whipe the  current table, uninstall the addon, and re-install it. I've tried reloading, removing all other addons. I also have access to change officer notes.

**Comment by Peleccotur** [comment]
Have your GM check the whitelisting. It sounds like you are not whitelisted. Clearing tables also clears your local whitelist. After that it goes on your officer privilieges until you receive the whitelist broadcast by another officer again.

**Comment by nicb33** [comment]
> Have your GM check the whitelisting. It sounds like you are not whitelisted. Clearing tables also clears your local whitelist. After that it goes on your officer privilieges until you receive the whitelist broadcast by another officer again.

My GM has mentioned he does not have anyone whitelisted, aka all officer's have the same accesses, wouldn't that setitng allow me to use my priveleges regularly without removing them? Or am I misunderstanding the whitelist function?

**Comment by Peleccotur** [comment]
Can you attach the SavedVariables file? So next time you cant go into the manage tab, log out and attach the file.
Reinstalling the addon itself doesnt change anything, so the issue is in the data. I would like to review said data

**Comment by nicb33** [comment]
> Can you attach the SavedVariables file? So next time you cant go into the manage tab, log out and attach the file. Reinstalling the addon itself doesnt change anything, so the issue is in the data. I would like to review said data
[SavedVariable Community DKP.txt](https://github.com/Vapok/CommunityDKP/files/7288576/SavedVariable.Community.DKP.txt)

Not exactly sure if this is sufficient, (I changed the changed variable file named "Blizzard_console" to a .txt file since it seems I couldn't poste a LUA file here. If this is fine, let me know and i'll upload another one in a few minutes when my privileges get removed

**Comment by Peleccotur** [comment]
"Blizzard_console"?
`<WoW Directory>\_classic_\WTF\Account\<YOUR ACCOUNT NAME>\SavedVariables\CommunityDKP.lua` is the correct file

**Comment by nicb33** [comment]
> "Blizzard_console"? `<WoW Directory>\_classic_\WTF\Account\<YOUR ACCOUNT NAME>\SavedVariables\CommunityDKP.lua` is the correct file

![image](https://user-images.githubusercontent.com/91982722/136088669-6f3e174e-2116-48d2-b230-0bed60229858.png)

I'm assuming it's the same thing? Perhaps a different name since it's from the classic game ?

**Comment by nicb33** [comment]
> "Blizzard_console"? `<WoW Directory>\_classic_\WTF\Account\<YOUR ACCOUNT NAME>\SavedVariables\CommunityDKP.lua` is the correct file

Derp Disregard my previous comment, i was looking in the wrong file like an idiot, this should be the file ( again not sure if .txt is fine, as cannot upload .lua) 
[Community DKP 2.txt](https://github.com/Vapok/CommunityDKP/files/7288704/Community.DKP.2.txt)

This would be the file when I do not have access to anything

**Comment by Peleccotur** [comment]
Somehow the whitelist is still set, by default this list is empty (no one whitelisted -> all officers can manage the addon)
If your nick is not in the list, your GM needs to double check his settings.


![Whitelist](https://user-images.githubusercontent.com/24406001/136090180-7cec0c0f-491f-495d-a75c-b63e1675b5fb.jpg)

**Comment by nicb33** [comment]
> Somehow the whitelist is still set, by default this list is empty (no one whitelisted -> all officers can manage the addon) If your nick is not in the list, your GM needs to double check his settings.
> 
> ![Whitelist](https://user-images.githubusercontent.com/24406001/136090180-7cec0c0f-491f-495d-a75c-b63e1675b5fb.jpg)

Thanks, I think that might be the issue, problem solved, much appreciated for the help!
