### ISSUE TITLE
Incremental Sync Issues

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#19]
we have two teams created: MC (the original, initial team was renamed) and BWL. We had a BWL raid in progress. Loot master starts a session and awards on time bonus.

I was not in raid, but online and watching Monolith. The people in raid believe the ontime bonus was applied to the BWL team; however, when I received the data it appeared in the MC team. Meaning, I could mouse-over the player in the BWL team and it showed no bonus, but if I mouseover them in the MC team, it shows the ontime bonus there.

Possibility: could incremental data sends being always applied to team 1 if the recipient is not in raid?

**Comment by thunk84** [comment]
after many tests, we have a 100% repro on this. Incremental syncs, such as on time bonus or just adjusting dkp, are going to the whichever team the *receiver* last selected. 

- I have chars A, B and C. 
- I am on our **MC team** and award 10 points to C 
- Char A last had MC opened, and when they check, they see +10 for C on the **MC team.** This is correct.
- Char B last had the BWL team opened and see +10 appear for C on the **BWL team**. This is incorrect

So the incremental data is being applied different on each receiver, based on whichever tab they last viewed.

**Comment by Vapok** [comment]
This is related to the #18 sync issues.  We're going to address it the same way, and change the signature of all of the syncs to include the team that it should be applied to, instead of trying to rely on individual context.

**Comment by Vapok** [comment]
We're considering this issue duplicative of #18 and will close it accordingly.
