### ISSUE TITLE
Change default column sorting to DKP

### ISSUE THREAD

**Issue by Anonomit** [Vapok/CommunityDKP#25]
I think that more users prefer to sort by DKP than Class.
The change would be made in Core.lua.
Current:
```lua
core.currentSort = "class"
```
Proposed:
```lua
core.currentSort = "dkp"
```

**Comment by Vapok** [comment]
This and #26 should be combined. I'm ok with changing the default to DKP, but instead if should read from the core.DB.settings for a new setting that keeps the currently selected sort from a previous sort.
