### ISSUE TITLE
One of the teams is greyed out

### ISSUE THREAD

**Issue by Anonomit** [Vapok/CommunityDKP#34]
I created a team for each raid and noticed that one of the team names has became greyed out after selecting it in the dropdown. Selecting other teams does not fix the issue. The same one is greyed out. An officer that I broadcasted to also noticed this in his UI with the same team.
![commdkp_ pngbug](https://user-images.githubusercontent.com/67178487/85209628-6f335700-b307-11ea-9f5b-674f3eb4cc01.PNG)

**Comment by Vapok** [comment]
@Taidtuskecyh Thoughts on this?

**Comment by Vapok** [comment]
@Anonomit Check to make sure you haven't initialized a raid.  Generally the teams will lock you out if there's another team with an initialized raid.  Taid worked on that piece of it.

**Comment by Anonomit** [comment]
This happens even when I'm not in a raid. Initializing the raid doesn't seem to change the appearance of the list. The same team was still greyed out.
To be clear, the dropdown does function correctly - it appears to be a cosmetic issue. I'm able to select any team, unless I've initialized raid.

**Comment by Taidtuskecyh** [comment]
fixed this with latest commit. Creation of loot history dropDownMenu was "disabling" third item
