### ISSUE TITLE
!dkp responses are indeterminate when using multiple teams

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#42]
**Describe the bug**
Using 3.0 r7: If user A whispers !dkp to user B, user B replies with a dkp value of whichever team user B last viewed. From User A's point of view, the reply is unpredictable.

**To Reproduce**

User A - regular raider. User B - officer. User C - officer.
1. User A wants to see team 1 DKP.
2. User B (officer) views Team 2, and closes CommunityDKP
3. User C (officer) views Team 1 and closes CommunityDKP
4 User A whispers User B. User B replies with team2 dkp as that's the last team he was viewing. User A, though, doesn't know which team the reply applies to. it appears to be random.
5. Since they're confused, user A whispers user C and receives team1 dkp. User A is confused because the officers are reporting two different values, and User A doesn't know how to force a response of team 1 dkp.

**Expected behavior**
When commDKP replies on User B, it should reply with User A's dkp in every team. And the output line should include the team name so it's clear which line applies to which team.

Or allow user A to query by team, such as "!dkp myName Black Wing Lair

**Screenshots**

**CommunityDKP Version**
3.0 r7:

**Additional context**

**Comment by Vapok** [comment]
Fantastic bug report!  Absolutely right.  I think the solution here is that !dkp reply with all teams that the player is apart of that officer can see. So it might look like:

[Team Name A] DKP 243
[Team Name B] DKP -12

**Comment by Vapok** [comment]
I've got it to where it does this now:
![image](https://user-images.githubusercontent.com/1264136/85349216-e6194d00-b4cb-11ea-8cae-fb0224b0cec9.png)

**Comment by Vapok** [comment]
I've got it to where it does this now:
![image](https://user-images.githubusercontent.com/1264136/85349241-f7faf000-b4cb-11ea-9785-4315a45c58f9.png)
