### ISSUE TITLE
Sync status light only shows status of team 1

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#44]
**Describe the bug**
The sync status light seems to always show status of team 1, no matter which team I select. We migrated data into a new team 2. I logged out. Another officer entered new info into team 2. I log in and the light shows green on both teams, even though I know another officer has more data than me.

**To Reproduce**
1. user A changes dkp on a member of team 2
2. user B logs
3. B's status light shows green no matter which team is selected

**Expected behavior**
Sync light would show status of the selected table

**Screenshots**

**CommunityDKP Version**
(e.g. 3.0.0)

**Additional context**

**Comment by Vapok** [comment]
Yep, I see what you're talking about. This might take a little effort to figure out. The Sync seeds are, touchy, to say the least.  Thanks for the bug report.

**Comment by Taidtuskecyh** [comment]
I will look into this later today. Will probably add some chat msgs as well if team isn't synced
