### ISSUE TITLE
Loot history and dkp history limiter sliders not retaining values

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#46]
**Describe the bug**
I have adjusted the loot history and dkp history sliders on the options tab, but after a reloadui, or logging back in, the sliders are reset to the max values. This happens regardless of whether I move the slide or type in a number directly.

**To Reproduce**
1. Options tab -> adjust Loot History limit or DKP History limit sliders
2. /reload or log out/log in
3. Open options tab, sliders have reverted back to max values

**Expected behavior**
Sliders retained the last value I set.

**Screenshots**

**CommunityDKP Version**
3.0.0

**Additional context**

**Comment by Vapok** [comment]
@thunk84 Can you verify for me that you are clicking the "Save Settings" button at the bottom of the options window before doing the reload?

**Comment by thunk84** [comment]
Ah, I bet that’s it. Totally forgot about that button. Will verify when I get home but am confident this will end up being user error.

**Comment by thunk84** [comment]
Confirmed. and closing.
