### ISSUE TITLE
Randomly during auctions, the icon showing up in the bid window is incorrect.

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#48]
**Describe the bug**
This has been in Monolith since I first started using it. Don't know how to reliably reproduce it. When starting an auction using /dkp bid <shift link>, all of the text labels and raid chat correctly describe the item. But sometimes, apparently randomly, the icon that appears in the bid windows does not match. When this happens, as near as I can tell, it happens to everyone equally because there's a surge of 39 players in Discord asking "wait, which item are we bidding on??"

It happened again tonight in BWL.

I don't know how to reproduce it on demand yet, but we've seen it in both MC and BWL. I figure this is a low priority bug, but wanted to document it. 

**To Reproduce**
Unfortunately, I don't have a clear repro.

**Expected behavior**
The icon displayed when an auction begins matches the actual item

**Screenshots**

**CommunityDKP Version**
This has been a Monolith bug since the very first version.

**Additional context**
We have not identified any clear patterns yet. It's happened with multiple loot masters and, as near as I can recall, on different items. We'll try to catch specific items next time and update this issue.

**Comment by matthintr** [comment]
I think I've read something in the past that this happens if the master looter reopens the loot window once items have been assigned. Maybe the addon stores the item positions only during the first loot event and they don't match anymore.

**Comment by thunk84** [comment]
@matthintr we'll watch for that. I'm feeling that's not the only case, though. I'm pretty sure I've opened the loot window, started auctions, and then started getting complaints about the mismatch. Thanks for the tip, though. We have another BWL team tonight and I'll watch for it.

**Comment by thunk84** [comment]
I have no idea if this is item-specific, but in our last BWL run, the affected item was "Pendant of the fallen dragon"

**Comment by Vapok** [comment]
It's not item dependent, but IT does have to do with the Master Looter window.  It sets the items on the first opening of the window, but in a lot of cases, especially on Nef, Ony, Rag (bosses with a lot of loot on them) if the master looter loots blues and greens first, then releases the window and picks the window back up, it reshuffles the items and causes the idex that the addon sees to be different than the item.  It's weird.  We can try to put some eyes on it, but I feel it might be more of an API limitation/player training issue.

**Comment by thunk84** [comment]
Copy that. I never loot the greens first, and I very rarely open/close/reopen the loot window. But I'll watch closely on tonight's run. Maybe I can narrow down the steps.

**Comment by Vapok** [comment]
Thanks to @lantisnt of EssentialDKP for lending the fix for the loot icon issue. I have implemented the fix they provided in the branch GH48
