### ISSUE TITLE
Not respecting RAID_CLASS_COLORS

### ISSUE THREAD

**Issue by xvwyh** [Vapok/CommunityDKP#49]
CommunityDKP, just like MonolithDKP, for some strange reason incorporates its own `tc_colors`/`core.CColors` duplicating the data that's already available as part of WoW's own `RAID_CLASS_COLORS` table. If the player has `RAID_CLASS_COLORS` changed (most often to change the color of shamans from pink to blue) - it's not replicated in CommunityDKP.

The hacky solution I've been using previously:
```diff
 for i = 1, #tc_classes do
 	local cname = tc_classes[i]
 	local lname = string.upper(cname)
-	core.CColors[lname] = tc_colors[cname]
+	core.CColors[lname] =
+	{
+		r = RAID_CLASS_COLORS[lname].r,
+		g = RAID_CLASS_COLORS[lname].g,
+		b = RAID_CLASS_COLORS[lname].b,
+		hex = RAID_CLASS_COLORS[lname].colorStr:sub(-6),
+	}
	table.insert(core.classes, lname)
end
```
But the best solution would be to get rid of `tc_colors`/`core.CColors` entirely and just use `RAID_CLASS_COLORS`.

**Comment by Vapok** [comment]
This has been implemented in master and will be sent out on next release.
