### ISSUE TITLE
DKP Values Stored as singles

### ISSUE THREAD

**Issue by caspervk** [Vapok/CommunityDKP#5]
It looks like DKP values are stored as [singles](https://en.wikipedia.org/wiki/Single-precision_floating-point_format) in some places:
![image](https://user-images.githubusercontent.com/2924482/83461587-64ed0e00-a469-11ea-9335-d1fc20176a72.png)

 On the other hand, the value is correctly shown in other places:
![image](https://user-images.githubusercontent.com/2924482/83461593-69192b80-a469-11ea-953a-aee2f82bbc4c.png)

I haven't looked through the code, but as with all currency, maybe the numbers should be stored as integers (in µDKP) or as [Decimal](https://en.wikipedia.org/wiki/Decimal_data_type)?

**Comment by caspervk** [comment]
For information, this issue was migrated from the original Roeshambo repository. I haven't tested if this issue persists in your fork.

**Comment by Vapok** [comment]
The issue still exists, I haven't made changes to this issue.

**Comment by caspervk** [comment]
I'm not sure https://github.com/Vapok/MonolithDKP/pull/6 fixes the underlying issue. The values are still stored as singles; are all values you could use representable? I better approach would probably be to store all DKP values as µDKP, and then only format it into decimals for the UI.
