### ISSUE TITLE
No import of MonolithDKP data and constant error messages

### ISSUE THREAD

**Issue by f90** [Vapok/CommunityDKP#59]
**Describe the bug**

I have Monolith DKP installed and wanted to switch over to CommunityDKP. Then installed CommunityDKP from twitch, started the game, got a notification by CommunityDKP to deactivate Monolith, where I pressed OK and nothing else happened afterwards. I deactivated MonolithDKP and /reloadui, but when opening /dkp menu I get many error messages (see below) and also my DKP table from monolith is not imported.

```
Message: Interface\AddOns\CommunityDKP\CommunityDKP.lua:451: Usage: GameTooltip:SetText("text" [, color, wrap])
Time: Fri Jun 26 12:13:25 2020
Count: 9
Stack: Interface\AddOns\CommunityDKP\CommunityDKP.lua:451: Usage: GameTooltip:SetText("text" [, color, wrap])
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:733: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693>
[C]: ?
[C]: in function `SetText'
Interface\AddOns\CommunityDKP\CommunityDKP.lua:451: in function <Interface\AddOns\CommunityDKP\CommunityDKP.lua:449>

Locals: errMsg = "Interface\AddOns\CommunityDKP\CommunityDKP.lua:451: Usage: GameTooltip:SetText("text" [, color, wrap])"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:514
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:495
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:480
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:488
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:328
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:380
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:456
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:297
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
```

```
Message: ...erface\AddOns\CommunityDKP\Modules\ManageEntries.lua:910: Usage: GameTooltip:SetText("text" [, color, wrap])
Time: Fri Jun 26 12:12:34 2020
Count: 2
Stack: ...erface\AddOns\CommunityDKP\Modules\ManageEntries.lua:910: Usage: GameTooltip:SetText("text" [, color, wrap])
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:733: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693>
[C]: ?
[C]: in function `SetText'
...erface\AddOns\CommunityDKP\Modules\ManageEntries.lua:910: in function <...erface\AddOns\CommunityDKP\Modules\ManageEntries.lua:908>

Locals: errMsg = "...erface\AddOns\CommunityDKP\Modules\ManageEntries.lua:910: Usage: GameTooltip:SetText("text" [, color, wrap])"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:514
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:495
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:480
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:488
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:328
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:380
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:456
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:297
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
```

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**Expected behavior**
Data is imported from Monolith and no error messages pop up when using /dkp

**CommunityDKP Version**
Community DKP Version 3.0.0-r16

**Comment by matthintr** [comment]
Mostly unrelated to your lua error: The migration dialog won't be there if MonolithDKP has empty tables or CommunityDKP already has entries.
Could you provide your `_classic_/WTF/Account/<account name>/SavedVariables/MonolithDKP.lua` and `_classic_/WTF/Account/<account name>/SavedVariables/CommunityDKP.lua` if you think there should be a migration dialog in your case?

**Comment by f90** [comment]
I had a fresh install of CommunityDKP so there was no CommunityDKP.lua beforehand at all. You should be able to replicate the issue of not having a migration window popup simply by installing CommunityDKP completely fresh.

Since we are using Monolith at the moment, its MonolithDKP.lua is also definitely not empty! But here it is so you can look into it

[MonolithDKP.zip](https://github.com/Vapok/CommunityDKP/files/4836397/MonolithDKP.zip)

**Comment by matthintr** [comment]
Thank you, which version of MonolithDKP are you on?

**Comment by f90** [comment]
The latest through Twitch, 2.1.2

**Comment by f90** [comment]
I manually copied my DKP table over to CommunityDKP. When I load only Community DKP with the lua file attached, I still get the 
```
Interface\AddOns\CommunityDKP\CommunityDKP.lua:451: Usage: GameTooltip:SetText("text" [, color, wrap])
```
error when hovering over the dropdown that shows our guild name in it. Maybe that's easier to replicate!

[CommunityDKP.zip](https://github.com/Vapok/CommunityDKP/files/4836599/CommunityDKP.zip)

**Comment by matthintr** [comment]
> The latest through Twitch, 2.1.2

Strange, the migration assistant checks if MonDKP_Loot["seed"] or MonDKP_DKPHistory["seed"] is > 0 to ensure that you're running an up-to-date and active version of MonolithDKP. In your export both seeds are = 0.

**Comment by f90** [comment]
I have no clue how that happened. If my case is an exception, we can ignore this problem for now, but keep in mind what the cause was if we encounter it with other players in the future. The manual installation worked for me (copy the saved variables text files), so it is not such a big deal I guess

**Comment by Vapok** [comment]
@f90 Were you able to move past this and get your table into CommunityDKP?

**Comment by f90** [comment]
Yes I installed the manual way - copying the MonolithDKP.lua saved variables file and renaming the MonDKP entries as shown in the Readme. Then CommDKP worked mostly fine and had all my DKP history. It was just confusing that CommDKP just wanted me to deactivate MonDKP instead of offering an import. And the Lua errors I have shown here are still there! So that's an issue independent of the automatic import not being triggered.

**Comment by Vapok** [comment]
So... I think that the hang-up is that you might have manually migrated the saved LUA before your first load up of CommunityDKP. The order of operations for the auto-migration is this:
1) Have MonolithdKP installed.
2) Install CommunityDKP through Curseforge
3) Turn on WoW and it will prompt for migration.

However, if CommunityDKP detects that it ALREADY has data, it will never prompt for a migration. It will simply detect that MonolithDKP is installed and ask you to uninstall it.

**Comment by Vapok** [comment]
That being said, sounds like you're good, I'm going to close this bug, but we'll monitor it and see if others have an issue. If so, we might have to add a little more "kid gloves" on that process and add a popup that says it detects CommunityDKP data already and will not migrate. @matthintr
