### ISSUE TITLE
Wrong display of deleted character names in bid records

### ISSUE THREAD

**Issue by f90** [Vapok/CommunityDKP#60]
**Describe the bug**
When you enable the logging of bids, and then hover an item in loot history, you will be shown who also previously won this item. But characters that have been deleted from the DKP table are not shown correctly. Seems like a small mistake with the color coding.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/23065103/85847723-39c7b700-b7a8-11ea-9120-c97c56ba36b3.png)

**CommunityDKP Version**
3.0.0-r16

**Comment by Vapok** [comment]
This is being fixed and will be included in Release 17.
