### ISSUE TITLE
Please add release number to in-addon version string

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#62]
**Is your feature request related to a problem? Please describe.**

Currently, the title box (with the logo and dice) shows the version number as 3.0.0, whereas the actual release is something like 3.0.0r17. I don't see anyway for users to find the actual release number in the addon.

**Describe the solution you'd like**

Modify the version number in the logo box to include the "rXX" suffix so when I ask a user which version they are on, I get a precise answer.

Also modify the message that appears in chat during UI startup to include the "rXX" suffix as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by Vapok** [comment]
This is implemented as of tag 3.0.1-r26!
