### ISSUE TITLE
Add version & release number of raid members as a new column in the DKP table

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#63]
**Is your feature request related to a problem? Please describe.**

As an officer, I can't tell who is using CDKP and who isn't. I also can't tell which version they're on. But I sure hear their complaints about perceived bugs! So the first question I always ask is, "which release are you on?"

**Describe the solution you'd like**

Another column in the DKP table showing the version number of each member would be a big help. To minimize the amount of syncing required, the officers should have a "request version number" button, by which they send a request to all raid members and all raid members respond with their version number.

**Describe alternatives you've considered**

You could do this for the entire guild rather than just raid members, but in our scenario that would rarely be useful. We primarily care about having everyone up-to-date during raids.

**Additional context**

**Comment by Vapok** [comment]
This has been implemented in r30
