### ISSUE TITLE
Spec / Role not being updated

### ISSUE THREAD

**Issue by DoomeD1982** [Vapok/CommunityDKP#64]
Both players using r17, both are officers in the guild, both using the same team, the spec/talent show from migration but on new team, they do not update.

1) Addon Version and Release e.g. 3.0.0-r17
2) What are your DKP Modes? (screenshot preferred)
![image](https://user-images.githubusercontent.com/58643765/85890166-b1461800-b7a1-11ea-9b53-354a0526702d.png)
![image](https://user-images.githubusercontent.com/58643765/85890210-bf943400-b7a1-11ea-9fbc-5dc43aa95ef5.png)
3) What is the issue you're seeing (screenshot preferred)
 -No error message
Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.
![image](https://user-images.githubusercontent.com/58643765/85890329-fd915800-b7a1-11ea-9d97-58c9898224c8.png)

**Comment by Vapok** [comment]
This appears to be connected to the work that we did to refactor the Seed information.  It's supposed to call **CommDKPQuery** when the Seed is sent, but that got left out.
