### ISSUE TITLE
Version check error

### ISSUE THREAD

**Issue by DoomeD1982** [Vapok/CommunityDKP#68]
V3.0.1-r30

On main table it works ok, but switching back to a different table i received the following.

Message: Interface\AddOns\CommunityDKP\CommunityDKP.lua:199: attempt to compare nil with string
Time: Sun Jun 28 00:11:22 2020
Count: 2
Stack: Interface\AddOns\CommunityDKP\CommunityDKP.lua:199: attempt to compare nil with string
Interface\AddOns\CommunityDKP\CommunityDKP.lua:199: in function <Interface\AddOns\CommunityDKP\CommunityDKP.lua:189>
[C]: in function `sort'
Interface\AddOns\CommunityDKP\CommunityDKP.lua:189: in function `SortDKPTable'
Interface\AddOns\CommunityDKP\CommunityDKP.lua:354: in function `func'
Interface\FrameXML\UIDropDownMenu.lua:958: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: a = <table> {
 previous_dkp = 0
 dkp = 0
 class = "MAGE"
 lifetime_gained = 0
 player = "Carpetbomb"
 role = "No Role Reported"
 lifetime_spent = 0
 rankName = "War Council"
 spec = "No Spec Reported"
 rank = 1
}
b = <table> {
 previous_dkp = 0
 dkp = 0
 class = "PRIEST"
 lifetime_gained = 0
 player = "Keffka"
 version = "Unknown"
 role = "No Role Reported"
 spec = "No Spec Reported"
 rankName = 3
 lifetime_spent = 0
 rank = 3
}
(*temporary) = nil
(*temporary) = "Unknown"
(*temporary) = "attempt to compare nil with string"
button = CommDKPDKPTableHeadersSortButtonClass {
 Id = "version"
 t = CommDKPSortColDropdown {
 }
 Ascend = true
 0 = <userdata>
}
id = "version"

![image](https://user-images.githubusercontent.com/58643765/85940948-827c8e80-b8d4-11ea-9bd0-7171f1dd4f58.png)

**Comment by Vapok** [comment]
Yep, I did know about this. it's because it hasn't indexed everyone.  I have a fix for it, that will go with r31.  The error doesn't break anything severe.

**Comment by Vapok** [comment]
Fixed has been released.
