### ISSUE TITLE
NOT sure just error

### ISSUE THREAD

**Issue by SpeedySaky** [Vapok/CommunityDKP#69]
Date: 2020-06-28 16:41:16
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\Core.lua line 366:
   attempt to perform arithmetic on field '?' (a nil value)
Debug:
   CommunityDKP\Core.lua:366: PurgeDKPHistory()
   CommunityDKP\init.lua:699: OnInitialize()
   CommunityDKP\init.lua:260: f()
   CommunityDKP\init.lua:246:
      CommunityDKP\init.lua:233
Locals:
self = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\CommunityDKP\Modules\DKPHistory.lua:28
 StartTimer = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:453
 ExportBox_Show = <function> defined @Interface\AddOns\CommunityDKP\Modules\exportDKP.lua:189
 MonolithMigrationCancelationPopup = <function> defined @Interface\AddOns\CommunityDKP\init.lua:1038
 tablelength = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:640
 StartBidTimer = <function> defined @Interface\AddOns\CommunityDKP\Modules\Bidding.lua:819
 SendSeedData = <function> defined @Interface\AddOns\CommunityDKP\init.lua:294
 ValidateDKPTable_DKP = <function> defined @Interface\AddOns\CommunityDKP\Modules\Validate.lua:66
 BidTimer = <unnamed> {
 }
 PurgeDKPHistory = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:338
 ValidateLootTable = <function> defined @Interface\AddOns\CommunityDKP\Modules\Validate.lua:229
 CreateSortBox = <function> defined @Interface\AddOns\CommunityDKP\Modules\LootHistory.lua:162
 ClearBidWindow = <function> defined @Interface\AddOns\CommunityDKP\Modules\Bidding.lua:670
 DKPHistoryFilterBox_Create = <function> defined @Interface\AddOns\CommunityDKP\Modules\DKPHistory.lua:74
 ValidateDKPTable_Final = <function> defined @Interface\AddOns\CommunityDKP\Modules\Validate.lua:135
 InitDbSchema = <function> defined @Interface\AddOns\CommunityDKP\init.lua:919
 MonolithMigrationConfirmationPopup = <function> defined @Interface\AddOns\CommunityDKP\init.lua:1021
 GetTable = <function> defined @Interface\AddOns\CommunityDKP\init.lua:704
 GetGuildRankGroup = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:265
 ZeroSumBank_Create = <function> defined @Interface\AddOns\CommunityDKP\Modules\ZeroSumBank.lua:88
 ZeroSumBank_Update = <function> defined @Interface\AddOns\CommunityDKP\Modules\ZeroSumBank.lua:70
 BroadcastTimer = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:414
 ClassGraph = <function> defined @Interface\AddOns\CommunityDKP\Modules\ClassGraph.lua:7
 PriceTable_Update = <function> defined @Interface\AddOns\CommunityDKP\Modules\LootPriceTab.lua:127
 StopRaidTimer = <function> defined @Interface\AddOns\CommunityDKP\Modules\RaidTimer.lua:100
 AwardPlayer = <function> defined @Interface\AddOns\CommunityDKP\Modules\RaidTimer.lua:35
 BidScrollFrame_Update = <function> defined @Interface\AddOns\CommunityDKP\Modules\Bidding.lua:1144
 MonolithMigrationDbBuild = <function> defined @Interface\AddOns\CommunityDKP\init.lua:1077
 ToggleExportWindow = <function> defined @Interface\AddOns\CommunityDKP\Modules\exportDKP.lua:376
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\CommunityDKP\Modules\Bidding.lua:736
 AddNewTeamToGuild = <function> defined @Interface\AddOns\CommunityDKP\Modules\ManageEntries.lua:327
 Bids_Set = <function> defined @Interface\AddOns\CommunityDKP\Modules\BidInterface.lua:450
 DKPHistory_Update = <function> defined @Interface\AddOns\CommunityDKP\Modules\DKPHistory.lua:257
 BidInterface_Toggle = <function> defined @Interface\AddOns\CommunityDKP\Modules\BidInterface.lua:217
 ValidateSender = <function> defined @Interface\AddOns\CommunityDKP\Modules\comm.lua:17
 CreateBidWindow = <function> defined @Interface\AddOns\CommunityDKP\Modules\Bidding.lua:1217
 reset_prev_dkp = <function> defined @Interface\AddOns\CommunityDKP\Modules\ManageEntries.lua:362
 GetTeamName = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:664
 ClassGraph_Update = <function> defined @Interface\AddOns\CommunityDKP\Modules\ClassGraph.lua:117
 CheckOfficer = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:236
 GetGuildName = <function> defined @Interface\AddOns\CommunityDKP\Core.lua:206
 DKPModes_Misc = <function> defined @Interface\AddOns\CommunityDKP\Modules\Modes\DKPModesMisc.lua:7
 DKPModes_Main = <function> defined @Interface\AddOns\CommunityDKP\Modules\Modes\DKPModesMain.lua:6
 DKPHistory_Reset = <function> defined @Interface\AddOns\CommunityDKP\Modules\DKPHistory.lua:48
 AdjustDKP = <function> defined @Interface\AddOns\CommunityDKP\Modules\AdjustDKP
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.40
  Altoholic, vClassic v1.13.4-014
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  CharacterStatsClassic, v3.5.4
  CommunityDKP, v3.0.0
  CoolDownWatcher, v1.7
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMSpellTimers, vr122
  DBMStatusBarTimers, v
  Details, v
  ElvUI, v1.24
  ElvUIEasyBuff, v1.1.7
  ElvUImMediaTagClassic, v1.64
  ElvUITauntAlert, v1.0
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  ExRT, v4160
  Gathering, v1.19
  GatherMate2, v1.45.5
  GTFO, v4.55
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.69
  MarkMe, v0.9.7
  MBB, v1.1.1
  MerInspect, v1.0.2
  MizusRaidTracker, vv0.85.2-classic
  NovaWorldBuffs, v1.66
  PlusOneRollTracker, v5.1
  Questie, v5.10.3
  RepHelperClassic, v1.13.4.1-release
  Restocker, v6.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=6e1)

**Comment by Vapok** [comment]
Can you please let me know what release of CommDKP you are using?  Also, in this case, can I get a copy of your Saved Variables LUA?

**Comment by SpeedySaky** [comment]
r31

[CommunityDKP.zip](https://github.com/Vapok/CommunityDKP/files/4842473/CommunityDKP.zip)

**Comment by SpeedySaky** [comment]
Date: 2020-06-28 17:11:30
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\init.lua line 178:
   attempt to index field 'DB' (a nil value)
Debug:
   CommunityDKP\init.lua:178: filterFunc()
   ElvUI\Modules\chat\Chat.lua:1192: ChatFrame_MessageEventHandler()
   ElvUI\Modules\chat\Chat.lua:1902: DisplayChatHistory()
   ElvUI\Modules\chat\Chat.lua:2367:
      ElvUI\Modules\chat\Chat.lua:2320
   [C]: ?
   ElvUI\Core\Core.lua:1222: CallLoadFunc()
   ElvUI\Core\Core.lua:1237: CallLoadedModule()
   ElvUI\Core\Core.lua:1263: InitializeModules()
   ElvUI\Core\Core.lua:1549: Initialize()
   ElvUI\init.lua:144:
      ElvUI\init.lua:143
   [C]: ?
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353:
      ..\FrameXML\UIParent.lua:352
   [C]: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.40
  Altoholic, vClassic v1.13.4-014
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  CharacterStatsClassic, v3.5.4
  CommunityDKP, v3.0.0
  CoolDownWatcher, v1.7
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMSpellTimers, vr122
  DBMStatusBarTimers, v
  Details, v
  ElvUI, v1.24
  ElvUIEasyBuff, v1.1.7
  ElvUImMediaTagClassic, v1.64
  ElvUITauntAlert, v1.0
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  ExRT, v4160
  Gathering, v1.19
  GatherMate2, v1.45.5
  GTFO, v4.55
  ItemRack, v
  LeatrixPlus, v1.13.69
  MarkMe, v0.9.7
  MBB, v1.1.1
  MerInspect, v1.0.2
  MizusRaidTracker, vv0.85.2-classic
  NovaWorldBuffs, v1.66
  PlusOneRollTracker, v5.1
  Questie, v5.10.3
  RepHelperClassic, v1.13.4.1-release
  Restocker, v6.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=6b6)

**Comment by SpeedySaky** [comment]
Date: 2020-06-28 16:36:42
ID: -5
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\init.lua line 213:
   attempt to index field 'DB' (a nil value)
Debug:
   (tail call): ?
   CommunityDKP\init.lua:213: filterFunc()
   ElvUI\Modules\chat\Chat.lua:1192: ChatFrame_MessageEventHandler()
   ElvUI\Modules\chat\Chat.lua:1902: DisplayChatHistory()
   ElvUI\Modules\chat\Chat.lua:2367:
      ElvUI\Modules\chat\Chat.lua:2320
   [C]: ?
   ElvUI\Core\Core.lua:1222: CallLoadFunc()
   ElvUI\Core\Core.lua:1237: CallLoadedModule()
   ElvUI\Core\Core.lua:1263: InitializeModules()
   ElvUI\Core\Core.lua:1549: Initialize()
   ElvUI\init.lua:144:
      ElvUI\init.lua:143
   [C]: ?
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353:
      ..\FrameXML\UIParent.lua:352
   [C]: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.40
  Altoholic, vClassic v1.13.4-014
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  CharacterStatsClassic, v3.5.4
  CommunityDKP, v3.0.0
  CoolDownWatcher, v1.7
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  Decursive, v2.7.7
  ElvUI, v1.24
  ElvUIEasyBuff, v1.1.7
  ElvUImMediaTagClassic, v1.64
  ElvUITauntAlert, v1.0
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  Gathering, v1.19
  GTFO, v4.55
  ItemRack, v
  LeatrixPlus, v1.13.69
  MarkMe, v0.9.7
  MBB, v1.1.1
  MerInspect, v1.0.2
  MizusRaidTracker, vv0.85.2-classic
  NovaWorldBuffs, v1.66
  PlusOneRollTracker, v5.1
  Questie, v5.10.3
  Restocker, v6.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  TrackingSwitcher, v1.1.3
  TranqRotate, v1.2.0
  WhereToGatherClassic, v1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=648)

**Comment by SpeedySaky** [comment]
that is all now

**Comment by Vapok** [comment]
This has been resolved in r32.  Thank you @SpeedySaky for the saved variables. This helped me reproduce all of the issues you were seeing!
