### ISSUE TITLE
CommunityDKP: CommunityDKP has not completed initialization

### ISSUE THREAD

**Issue by KingWataba** [Vapok/CommunityDKP#72]
3.0.0-r32

Installed Community started wow I migrated to Community. Disabled Monolith and then reloaded.
![WowClassic_dM0NSgs60u](https://user-images.githubusercontent.com/67564710/85962129-a2638f00-b974-11ea-84ca-2b585e26f0e4.png)

Date: 2020-06-28 19:04:11
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua line 30:
   attempt to perform arithmetic on a nil value
Debug:
   [C]: ?
   ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:30:
      ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:28
   [C]: sort()
   ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:28:
      ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:27
   ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:55:
      ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:46
   ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:164: CreateSortBox()
   ...nterface\AddOns\CommunityDKP\Modules\LootHistory.lua:413: LootHistory_Update()
   CommunityDKP\ConfigMenuTabs.lua:291: ConfigMenuTabs()
   CommunityDKP\CommunityDKP.lua:266: CreateMenu()
   CommunityDKP\init.lua:644:
      CommunityDKP\init.lua:643
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.7 
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, vClassic v1.13.4-014
  Atlas, vv1.47.03.11304.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CallbackHandler10, v
  CharacterNotes, v8.2.7
  ClassicAuraDurations, v1.13.58
  ClassicCastbars, vv1.3.8
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.3
  ClassicSpellActivations, v
  CommunityDKP, v3.0.0
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DBMCore, v1.13.51
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  DejaClassicStats, v1304r002
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  Grid2, vr955
  Grid2LDB, vr955
  Grid2RaidDebuffs, vr955
  GroupCalendar, v
  GTFO, v4.55
  GuildRosterManager, v1.88
  honorspy, v1.7.3
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.69
  LeatrixPlus, v1.13.69
  LibStub, v
  LoseControl, v1.05
  Necrosis, v7.2
  NeedsFoodBadly, v0.4.1
  OmniCC, v8.3.5
  orbSellAndRepair, v1.0.1
  Prat30, v3.8.25
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Questie, v5.10.3
  Scrap, v8.3.2
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.0.27
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  TitanClassic, v1.2.3.11304
  TitanClassicAmmo, v1.2.3.11304
  TitanClassicBag, v1.2.3.11304
  TitanClassicClock, v1.2.3.11304
  TitanClassicGold, v1.2.3.11304
  TitanClassicLocation, v1.2.3.11304
  TitanClassicLootType, v1.2.3.11304
  TitanClassicPerformance, v1.2.3.11304
  TitanClassicRegen, v1.2.3.11304
  TitanClassicRepair, v1.2.3.11304
  TitanClassicVolume, v1.2.3.11304
  TitanClassicXP, v1.2.3.11304
  TitanSocial, v1.13.3
  TomTom, vv11304-1.1.2
  totalRP3, v1.6.11
  totalRP3Data, v
  WeakAuras, v2.17.8
  WIM, v3.8.10
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=b82)

**Comment by KingWataba** [comment]
[CommunityDKP.txt](https://github.com/Vapok/CommunityDKP/files/4843461/CommunityDKP.txt)

**Comment by KingWataba** [comment]
[CommunityDKP.txt](https://github.com/Vapok/CommunityDKP/files/4843475/CommunityDKP.txt)

**Comment by Vapok** [comment]
This is because of bad data in the CommDKP_Loot table that came over from the migration. 
![image](https://user-images.githubusercontent.com/1264136/85969430-976d2680-b995-11ea-9a03-6481d418c4f6.png)

I've made a change that will ensure that the data is as it's expected since we do a fair amount of string manipulation to it.

**Comment by Vapok** [comment]
Fixed in r33
