### ISSUE TITLE
NOT sure

### ISSUE THREAD

**Issue by SpeedySaky** [Vapok/CommunityDKP#73]
Date: 2020-06-29 05:56:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CommunityDKP\init.lua line 213:
   attempt to index field 'DB' (a nil value)
Debug:
   CommunityDKP\init.lua:213: filterFunc()
   ElvUI\Modules\chat\Chat.lua:1192: ChatFrame_MessageEventHandler()
   ElvUI\Modules\chat\Chat.lua:1902: DisplayChatHistory()
   ElvUI\Modules\chat\Chat.lua:2367:
      ElvUI\Modules\chat\Chat.lua:2320
   [C]: ?
   ElvUI\Core\Core.lua:1222: CallLoadFunc()
   ElvUI\Core\Core.lua:1237: CallLoadedModule()
   ElvUI\Core\Core.lua:1263: InitializeModules()
   ElvUI\Core\Core.lua:1549: Initialize()
   ElvUI\init.lua:144:
      ElvUI\init.lua:143
   [C]: ?
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353:
      ..\FrameXML\UIParent.lua:352
   [C]: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.40
  Altoholic, vClassic v1.13.4-014
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.5.2
  CharacterStatsClassic, v3.5.4
  CommunityDKP, v3.0.0
  CoolDownWatcher, v1.7
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  ElvUI, v1.24
  ElvUIEasyBuff, v1.1.7
  ElvUImMediaTagClassic, v1.64
  ElvUITauntAlert, v1.0
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  Gathering, v1.19
  GTFO, v4.55
  ItemRack, v
  KillTrack, vv1.13.0
  LeatrixPlus, v1.13.69
  MarkMe, v0.9.7
  MBB, v1.1.1
  MerInspect, v1.0.2
  MizusRaidTracker, vv0.85.2-classic
  NovaWorldBuffs, v1.66
  PlusOneRollTracker, v5.1
  Questie, v5.10.3
  RepHelperClassic, v1.13.4.1-release
  Restocker, v6.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.20
  TrackingSwitcher, v1.1.3
  TranqRotate, v1.2.0
  WhereToGatherClassic, v1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=670)

version r32

on load
[CommunityDKP.zip](https://github.com/Vapok/CommunityDKP/files/4843715/CommunityDKP.zip)

**Comment by Vapok** [comment]
Fixed in r33 already.
