### ISSUE TITLE
DKP points stored in officer notes

### ISSUE THREAD

**Issue by SpeedySaky** [Vapok/CommunityDKP#78]
Ok

this is a feature that was active in early releases of monolith and it was a good one because people could see their dkp without the adddon,but people have it 
but
every now and then there happened to be some bug between syncing with GM and officers so it would be nice that GM could store newest DKP status in officer note when they broadcast,or make weekly delay or what,just to have some backup regardless addon backup in WTF folder
so,not and automaticall officer note input,but manual option

this is something guildies proposed as an option because we used monolith back then when it was possible,then it was removed and they liked that option

**Comment by Vapok** [comment]
Officer notes used to be the way a lot of add-ons stored guild wide data... but we soon learned that it wasn't reliable.  and only officers could see it. In the same manner, people can just "!dkp" to see their dkp in the guild, raid, or whisper and they can "!dkp <playername>" to see someone else's.
