### ISSUE TITLE
Auto Reward DKP doesn't work

### ISSUE THREAD

**Issue by h3xp** [Vapok/CommunityDKP#81]
The DKP after killing a boss don't get automatically awarded even though it is turned on in DKP Modes -> Misc -> Auto Award DKP

1) Addon Version and Release e.g. 3.0.0-r7

v3.0.1-r34

2) What are your DKP Modes? (screenshot preferred)

![DKP Mode](http://nocent.xyz/u/19.47.00-01.07.20.png)
![DKP Mode Misc](http://nocent.xyz/u/19.47.16-01.07.20.png)

**Expected behavior**
After killing a boss the DKP set in Default DKP Award Values should automatically be awarded to the raid members.

**Comment by Vapok** [comment]
@h3xp This has been modified in recent changes to require the Raid to be Initialized in the Addon before awarding automatic rewards.  What needs to be adjusted here is the wording on the tooltips for Auto Award items.  To get Auto Award DKP, you'll want to make sure you Initialize the Raid beforehand. 

![image](https://user-images.githubusercontent.com/1264136/86276045-35cdd780-bba2-11ea-8258-a5af4fe50fc5.png)

If you don't want the auto awarded interval, set the values as show in the screen shot.
