### ISSUE TITLE
Broadcast Settings

### ISSUE THREAD

**Issue by DoomeD1982** [Vapok/CommunityDKP#88]
When broadcasting the settings i receive an error 
![image](https://user-images.githubusercontent.com/58643765/86877258-4c40cb00-c09b-11ea-9c7e-8390988a0a0f.png)

![image](https://user-images.githubusercontent.com/58643765/86877279-5c58aa80-c09b-11ea-9423-c91b9e501bbc.png)

Community DKP 3.1.0-r37

**Comment by Vapok** [comment]
Fix to go out with r38
