### ISSUE TITLE
When disabled max item DKP a value of 0 DKP is displayed

### ISSUE THREAD

**Issue by thomas-worm** [Vapok/CommunityDKP#91]
**Describe the bug**
When deselected "Custom" from the max item bidding value, then bidders see a max DKP value of 0. They are expecting to see their DKP amount they can bid at max (the DKP they have in their account)

1) Addon Version and  dRelease e.g. 3.0.0-r7
v3.1.0

2) What are your DKP Modes? (screenshot preferred)
![](https://i.ibb.co/vH13qvN/dkpmodes.png)

3) What is the issue you're seeing (screenshot preferred)
0 is displayed as Max DKP in the bidding window. It should be removed or replaced with the max DKP on bidders account. Current solution results to bidders thinking they aren't allowed to bid.

**To Reproduce**
1. Open bidding window with item link
2. Deselect "custom" besides max dkp
3. Start bidding

**Expected behavior**
No Max DKP is displayed or bidders DKP amount is displayed as Max DKP

**CommunityDKP Version**
v3.1.0

**Comment by Vapok** [comment]
@thomas-worm Can you post a screenshot of your Mode's window?  What you provided was the Misc tab.

**Comment by Vapok** [comment]
@thomas-worm This is being attempted to be fixed in release 39.  Please test it and let me know if it's behaving as expected.
