### ISSUE TITLE
Shift click loot to activate community dkp

### ISSUE THREAD

**Issue by Mageofwar-grs** [Vapok/CommunityDKP#92]
**When I shift click to start the dkp nothing happens. 
I'f Im the Raid leader with master loot, don't I just shift click the loot to start the DKPs?
I just installed the newest version off of twitch.
The DKP mode is min bid value.

Will this only work if it's a Raid instance or can it work in a 5 man. 
Please advise. 

And thank you for all your hard work.

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**CommunityDKP Version**
(e.g. 3.0.0)

**Additional context**

**Comment by Vapok** [comment]
@Mageofwar-grs - Can you try holding down both the Shift and the Alt keys when clicking in the loot window?  

Also, when not in a raid, auto-loot has to be turned off.

**Comment by Mageofwar-grs** [comment]
Yeah I see that you guys use shift and alt now. Thank you for your quick response. I appreciate it

Sent from my iPhone

On Jul 9, 2020, at 10:09 PM, Pete Navarra <notifications@github.com> wrote:

﻿

@Mageofwar-grs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMageofwar-grs&data=02%7C01%7C%7C636eb5c26a4b47647d1b08d82476573b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637299437968475968&sdata=In2eJKbk8kTiGAf4YB5OPHjxx0aoqwmsIbsoUmct3Lw%3D&reserved=0> - Can you try holding down both the Shift and the Alt keys when clicking in the loot window?

Also, when not in a raid, auto-loot has to be turned off.
