### ISSUE TITLE
Recent update, maybe 3.1.1-r42 has duplicated, instead of merging last 2 weeks push

### ISSUE THREAD

**Issue by jvolkenant** [Vapok/CommunityDKP#93]
**Describe the bug**
We had a few people missing data from our raid on Sunday 7/5/2020. Today, before our MC run, we had one of our officers who had the data, push 2 week merge to our guild. It appears that all data from the last 2 got duplicated.

1) Addon Version and Release: 3.1.1-r47 )

2) What are your DKP Modes? (screenshot preferred)
![image](https://user-images.githubusercontent.com/10521453/87215627-388ca300-c2ed-11ea-8b82-c9f8e57b4105.png)
![image](https://user-images.githubusercontent.com/10521453/87215628-42160b00-c2ed-11ea-8c46-ae83c5e189c9.png)

3) What is the issue you're seeing
Entries are duplicated (highlighted blue in the first image), we don't allow negative dkp
![image](https://user-images.githubusercontent.com/10521453/87215549-7dfca080-c2ec-11ea-84db-4f2d8eefe48f.png)
![image](https://user-images.githubusercontent.com/10521453/87215621-2f033b00-c2ed-11ea-9480-31f4ee5c7651.png

**To Reproduce**
1. Do a guild, merge last 2 weeks broadcast
![image](https://user-images.githubusercontent.com/10521453/87215685-bb156280-c2ed-11ea-9c14-a5078fac9d32.png)

2. check users who had data over last 2 weeks to see the entries are duplicated

**Expected behavior**
Data is merged, sans the duplication

**Screenshots**

**CommunityDKP Version**
(e.g. 3.0.0)

**Additional context**

**Comment by Vapok** [comment]
Can you attach your saved variables for me?

**Comment by jvolkenant** [comment]
Uploaded here: [https://volkenant.net/CommunityDKP.lua](https://volkenant.net/CommunityDKP.lua)

**Comment by Vapok** [comment]
Not denying there's an issue, but I'm not able to reproduce in my test environment.  Was the officer that did the sync have r42 installed?

**Comment by Vapok** [comment]
@jvolkenant So... I see Qual has the latest indexes in some of the tables, but they are rockin' version r37 which introduced this issue.

```
                               ["Quel"] = {
					["previous_dkp"] = 0,
					["dkp"] = 0,
					["class"] = "None",
					["lifetime_gained"] = 0,
					["role"] = "Caster DPS",
					["version"] = "v3.1.0-r37",
```

**Comment by Vapok** [comment]
Important to get everyone to update to the latest version. Sorry about this error. One of the reasons why I changed the minor version to 3.1.1, so that the addon would yell at people out of data.  Based on your file, there's a wide swather of versions.

![image](https://user-images.githubusercontent.com/1264136/87216165-f1150f80-c30a-11ea-9a07-d3b097f70532.png)

**Comment by jvolkenant** [comment]
Quel is traveling, and should have tables before the push that occurred today and work out how we can get synced and up to date. We'll tell our raiders to get their versions updated as well.

Thanks
