### ISSUE TITLE
Receiving a 2-week push from another officer gave LUA error

### ISSUE THREAD

**Issue by thunk84** [Vapok/CommunityDKP#96]
**Describe the bug**
A clear and concise description of what the bug is. This includes the following information:

Installed r43 and started WoW. Another officer sent me a 2-week push. CDKP generated the following LUA error:

![image](https://user-images.githubusercontent.com/59933050/87228959-cf934280-c361-11ea-96ef-389cc8cf81f7.png)

1) Addon Version and Release e.g. 3.0.0-r7
v3.1.1-r43. The sending officer was also on r43

2) What are your DKP Modes? (screenshot preferred)

![image](https://user-images.githubusercontent.com/59933050/87229018-12edb100-c362-11ea-9099-f7c045a055eb.png)

![image](https://user-images.githubusercontent.com/59933050/87229028-21d46380-c362-11ea-9e60-124eb0d2471c.png)

3) What is the issue you're seeing (screenshot preferred)

Additionally, depending on the nature of the issue, we might ask for your SavedVariabled CommunityDKP.lua file.

[CommunityDKP.lua .txt](https://github.com/Vapok/CommunityDKP/files/4907193/CommunityDKP.lua.txt)
[CommunityDKP.lua.bak .txt](https://github.com/Vapok/CommunityDKP/files/4907196/CommunityDKP.lua.bak.txt)

**To Reproduce**
1. Install r43
2. Start WoW
3. Have another officer also on r43 push

**Expected behavior**

No errors :)

**Screenshots**

**CommunityDKP Version**
(e.g. 3.0.0)
3.1.1 r43 

**Additional context**

**Comment by Vapok** [comment]
@thunk84 Which team were you trying to sync?

**Comment by Vapok** [comment]
Nevermind, I found the issue.

**Comment by Vapok** [comment]
Fixed in release 44
