### ISSUE TITLE
Ability to set Default Maximum Bid Value fields to always display user's max DKP by default

### ISSUE THREAD

**Issue by LeviosaMimosa** [Vapok/CommunityDKP#97]
**Is your feature request related to a problem? Please describe.**
Currently on the DKP Bid Window, there's a checkbox than can be unchecked per item to have the user's bid box show their personal MAX dkp display in their bidding window. It's a bit tedious to remember to uncheck this box every time an item drops. It also requires additional training and cognitive load to remember to use this feature when teaching new persons to run loot. A default setting to reduce this extra step would be very helpful.

**Describe the solution you'd like**
Where we can currently type "0" in the Default Maximum Bid Values fields to not set a max, it would be nice to type "MAX" or some other verbiage into that same field to display a users maximum DKP by default. 

**Describe alternatives you've considered**
Alternative: An option to have the Maximum Bid "Custom" box unchecked by default.

**Additional context**
Our guild is currently running the following:

DKP Mode: Minimum Bid Value
[x] Sub Zero Bidding
[x] Allow Negative Bidders

Max Bid Button Behavior: Max DKP

**Comment by Vapok** [comment]
I've made a change where the system will remember the last set value of the checkbox. This will be applied in release 44.
