### ISSUE TITLE
DKP loot filter tab has broken selection?

### ISSUE THREAD

**Issue by f90** [Vapok/CommunityDKP#98]
**Describe the bug**
In the loot history, the dropdown on the top right has a bug: It has an empty list entry, and selecting the second seems to select both at the same time:
![grafik](https://user-images.githubusercontent.com/23065103/87258145-c3ae9a00-c4a1-11ea-94a4-da2ade44fc47.png)

It's just a visual bug though since the non-empty entries can be selected fine and show the required content in the window frame

This is with a completely fresh install of CommunityDKP, right after importing old Monolith DKP data.

**To Reproduce**
1. Go to Loot History
2. Click on the drop down on the top right

**CommunityDKP Version**
3.1.2-r44

**Comment by Vapok** [comment]
This might be a translation variable missing

**Comment by f90** [comment]
One issue is that the "ITEMS" entry in the German localisation table is missing, which is accessed for the last item in the dropdown list. Might be missing from other languages too? For English it's there though:
https://github.com/Vapok/CommunityDKP/blob/806512bc2f3187b326041b218076f1050e500c31/Localization/Localization.en.lua#L320

But the third entry should just be a separator (blank space), not selectable at all with a checkmark icon. So maybe that's not related to the translation but rather the UI code?

**Comment by Vapok** [comment]
Should be fixed in the next release. r46
