### ISSUE TITLE
Remove "bidder has passed" messages

### ISSUE THREAD

**Issue by Anonomit** [Vapok/CommunityDKP#99]
When I'm hosting a bid, I get a chat message every time a player passes. The only way to hide these messages is to suppress all addon notifications.

I'd like the messages removed entirely. The offending line is in comm.lua (for some reason).

I've been commenting out that particular line every update, but I've started to wonder why it's even there. It's not localized, and I can't look through 40 messages every bid to figure out who still hasn't passed on the item. An interface to show who has not yet passed would be nice, but regardless of that feature being added I think the messages should go.

```lua
if _objReceived.Data == "pass" then
  CommDKP:Print(sender.." has passed.")
  return
```

**Comment by Vapok** [comment]
r45
